# NOTE: This is the docker-compose for local development. For the production docker-compose, see README.md
version: "3"
services:
  scooch:
    # image: scooch
    build: .
    volumes:
      - ./public/slides:/slides
      # - ./templates:/templates
    ports:
      - 3000:3000
    restart: unless-stopped